name: PhxClient CI

on: push

jobs:
  test:
    runs-on: ubuntu-18.04

    container:
      image: elixir:1.9.1-slim
      env:
        MIX_ENV: test

    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd phx_client
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: |
          cd phx_client
          mix test
  # release:
  #   name: Create Release
  #   needs: test
  #   container:
  #     image: elixir:1.9.1-slim
  #     env:
  #       MIX_ENV: prod
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Initial setup
  #     - run: |
  #         cd phx_client
  #         mix deps.get --only prod
  #         MIX_ENV=prod mix compile
  #     - name: Compile assets
  #       run: |
  #         cd phx_client
  #         npm run deploy --prefix ./assets
  #         mix phx.digest
  #     - name: Create Release
  #     - run: |
  #         cd phx_client
  #         mix release
  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: phx_client
  #         path: release
